name: mem_store_client
description: "Meme store client"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  auto_route: ^7.8.4
  bloc: ^8.1.3
  dart_mappable: ^4.2.0
  equatable: ^2.0.5
  fetch_client: ^1.1.0-wasm
  flex_color_scheme: ^7.3.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_svg: ^2.0.9
  global_configuration: ^2.0.0
  http: ^1.2.1
  lru_cache:
    git: https://github.com/Zekfad/lru_cache
  meta: ^1.12.0
  photo_view: ^0.14.0
  rxdart: ^0.27.7
  talker: ^4.1.0
  talker_flutter: ^4.1.0
  infinite_scroll_pagination: ^4.0.0
  form_bloc: ^0.31.0
  reactive_forms: ^16.1.1
  reactive_forms_annotations: ^4.3.0
  file_picker: ^8.0.0+1

dev_dependencies:
  auto_route_generator: ^7.3.2
  build_runner:
  dart_mappable_builder: ^4.2.0
  # flutter_test:
  #   sdk: flutter
  reactive_forms_generator: ^4.5.2
  zekfad_lints: ^2.0.0

dependency_overrides:
  meta: ^1.12.0

flutter:
  assets:
    - assets/icons/
    - assets/images/
  uses-material-design: true
