name: mem_store_client
description: "Meme store client"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dart_mappable: ^4.2.0
  auto_route: ^6.1.0
  flutter_bloc: ^8.1.3
  global_configuration: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  dart_mappable_builder: ^4.2.0
  zekfad_lints: ^2.0.0
  build_runner:

flutter:
  uses-material-design: true
